export const SET_POOL = "SET_POOL";
export const INIT_PREDICTVERSE = "INIT_PREDICTVERSE";
export const INIT_PREDICTVERSE_FAILED = "INIT_PREDICTVERSE_FAILED";
export const INIT_PREDICTVERSE_SUCCESS = "INIT_PREDICTVERSE_SUCCESS";
