export const INIT_PREDICTVERSE_MARKET = "INIT_PREDICTVERSE_MARKET";
export const INIT_PREDICTVERSE_MARKET_FAILED =
    "INIT_PREDICTVERSE_MARKET_FAILED";
export const INIT_PREDICTVERSE_MARKET_SUCCESS =
    "INIT_PREDICTVERSE_MARKET_SUCCESS";
export const SET_BORROWED_DATA = "SET_BORROWED_DATA";
