export const INIT_LOSER_POOL = "INIT_LOSER_POOL";
export const INIT_LOSER_POOL_SUCCESS = "INIT_LOSER_POOL_SUCCESS";
export const INIT_LOSER_POOL_FAILED = "INIT_LOSER_POOL_FAILED";
export const GET_PAST_LOSER_POOLS = "GET_PAST_LOSER_POOLS";
export const GET_PAST_LOSER_POOLS_FAILED = "GET_PAST_LOSER_POOLS_FAILED";
export const GET_PAST_LOSER_POOLS_SUCCESS = "GET_PAST_LOSER_POOLS_SUCCESS";
export const SET_LOSER_POOL = "SET_LOSER_POOL";

export const INIT_WINNER_POOL = "INIT_WINNER_POOL";
export const INIT_WINNER_POOL_SUCCESS = "INIT_WINNER_POOL_SUCCESS";
export const INIT_WINNER_POOL_FAILED = "INIT_WINNER_POOL_FAILED";
export const GET_PAST_WINNER_POOLS = "GET_PAST_WINNER_POOLS";
export const GET_PAST_WINNER_POOLS_FAILED = "GET_PAST_WINNER_POOLS_FAILED";
export const GET_PAST_WINNER_POOLS_SUCCESS = "GET_PAST_WINNER_POOLS_SUCCESS";
export const SET_WINNER_POOL = "SET_WINNER_POOL";
