export const GET_LIVE_MATCHES = "GET_LIVE_MATCHES";
export const SET_LIVE_MATCHES = "SET_LIVE_MATCHES";
export const GET_LIVE_MATCHES_FAILED = "GET_LIVE_MATCHES_FAILED";
export const GET_LIVE_MATCHES_SUCCESS = "GET_LIVE_MATCHES_SUCCESS";

export const GET_UPCOMING_MATCHES = "GET_UPCOMING_MATCHES";
export const SET_UPCOMING_MATCHES = "SET_UPCOMING_MATCHES";
export const GET_UPCOMING_MATCHES_FAILED = "GET_UPCOMING_MATCHES_FAILED";
export const GET_UPCOMING_MATCHES_SUCCESS = "GET_UPCOMING_MATCHES_SUCCESS";

export const GET_USER_PAST_PREDICTIONS = "GET_USER_PAST_PREDICTIONS";
export const SET_USER_PAST_PREDICTIONS = "SET_USER_PAST_PREDICTIONS";
export const GET_USER_PAST_PREDICTIONS_FAILED = "GET_USER_PAST_PREDICTIONS_FAILED";
export const GET_USER_PAST_PREDICTIONS_SUCCESS = "GET_USER_PAST_PREDICTIONS_SUCCESS";

export const SET_SPORT_PREDICTION_DATA = "SET_SPORT_PREDICTION_DATA";

export const SET_PREDICT_MATCH_MODAL = "SET_PREDICT_MATCH_MODAL";

export const SET_CLAIM_MODAL = "SET_CLAIM_MODAL";

export const ADD_NEW_UPCOMING_MATCH = "ADD_NEW_UPCOMING_MATCH";

export const INCREMENT_MATCH_PREDICTION_FILLED_SLOT = "INCREMENT_MATCH_PREDICTION_FILLED_SLOT";