export const SET_POOL = "SET_POOL";
export const SET_USER_POOL_DETAILS = "SET_USER_POOL_DETAILS"
export const INIT_STAKING = "INIT_STAKING";
export const INIT_STAKING_FAILED = "INIT_STAKING_FAILED";
export const INIT_STAKING_SUCCESS = "INIT_STAKING_SUCCESS";
export const INIT_FARMING = "INIT_FARMING";
export const INIT_FARMING_FAILED = "INIT_FARMING_FAILED";
export const INIT_FARMING_SUCCESS = "INIT_FARMING_SUCCESS";
